version: '3'
services:
  # fridayparty fe service
  fridayparty-fe:
    image: fridayparty/client:latest
    networks:
      - fridayparty-network
    expose:
      - 3000

  # fridayparty api service
  fridayparty-api:
    image: fridayparty/api:latest
    networks:
      - fridayparty-network
    expose:
      - 5000

  # nginx proxy service
  webserver:
    image: fridayparty/proxy:latest
    restart: always
    depends_on:
      - fridayparty-fe
      - fridayparty-api
      - strapi-be
    networks:
      - fridayparty-network
    ports:
      - 80:80
      - 443:443

  # strapi backend service
  strapi-be:
    image: strapi/strapi
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - mongo-db
    networks:
      - fridayparty-network
    volumes:
      - fridayparty-strapi:/srv/app
    ports:
      - 1337:1337

  # mongo db service
  mongo-db:
    image: mongo
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - fridayparty-network
    volumes:
      - fridayparty-data:/data/db
    expose:
      - 27017

networks:
  fridayparty-network:

volumes:
  fridayparty-data:
  fridayparty-strapi:
