import Head from 'next/head'
import styles from '../styles/Home.module.css'

function Home(props) {
  const { todos } = props

  return (
    <div className={styles.container}>
      <Head>
        <title>Client App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title}>
          Friday Party Client
        </h3>
        <br/>
        {todos.map((todo) => <div key={todo.id}>{todo.title}</div>)}
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  return { props:{ todos: [] } }
}

export default Home